name: Publish to PyPI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pyroxi/
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build distribution
        run: python -m build

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # Uses trusted publisher authentication (no API token needed)
        # Make sure this repository is configured as a trusted publisher on PyPI
